name: Github Pages

on:
  push:
    branches:
      - master
    paths:
      - 'website/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        working-directory: ./website
        run: npm install
      - name: Build
        working-directory: ./website
        run: npm run build --if-present
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./website/build
